### ISSUE TITLE
%a conversion in __mingw_printf misprints integer values

### ISSUE THREAD

**Issue by vacaboja** [msys2/msys2#35] opened 2017-06-06 21:15 UTC
On a fresh install of msys2 (with the binary installer on the home page) on windows 10. Perform the following steps.

1 - Install mingw-w64-x86_64-gcc
2 - Compile the following code
#include <stdio.h>
int main() { __mingw_printf("%a\n", 1.0); return 0; }
3 - Run it.

The expected result is 0x1p0, however I get 0x0p-63. Oddly enough the function seems to misprint only integers, 3.14, for instance, seems to be printed correctly.

**Comment by elieux** [comment] 2017-06-08 06:35
Could you report this bug to the mingw-w64 project?

**Comment by vacaboja** [comment] 2017-06-08 16:57
Thanks, I found that the bug has already been reported.
https://sourceforge.net/p/mingw-w64/bugs/459/
I suggested a solution in a comment, let's see if they make the correction... I do not know whether I should close the bug here or leave it open, please do as you prefer.

**Comment by elieux** [comment] 2017-06-12 06:50
Let's leave it open for now.

**Comment by vacaboja** [comment] 2017-06-19 23:08
Just a little update: I received an email that the mingw-w64 developers have pushed the fix to master, so I believe the bug will be fixed in the next version.

**Comment by mati865** [comment] 2017-06-20 08:44
Unfortunately it's still wrong according to https://sourceforge.net/p/mingw-w64/bugs/459/#24b7

**Comment by vacaboja** [comment] 2017-06-20 17:24
No, as far as we know the fix is in spec. The observation of LH_Mouse is merely meant to say that it does not produce the same result as MSVCRT. In the test case presented both implementations behaved consistently with the C99 specs.

Although the mingw-w64 implementation is different from both MSVCRT and glibc, and even though I would not have chosen that algorithm myself, still it is neither unreasonable nor incorrect.

**Comment by elieux** [comment] 2017-06-22 18:00
I'm gonna tentatively close this ticket, assuming the fix gets packaged at some point, but if someone feels the issue is not resolved, we can re-open.

**Closed by elieux** 2017-06-22 18:00 UTC
